"""review model created

Revision ID: 103f762aced6
Revises: 8821c7164fb0
Create Date: 2024-09-06 17:21:31.377958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '103f762aced6'
down_revision: Union[str, None] = '8821c7164fb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('uuid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('product_uuid', sa.Uuid(), nullable=False),
    sa.Column('author_uuid', sa.Uuid(), nullable=False),
    sa.Column('text', sa.String(length=1000), nullable=False),
    sa.Column('rate', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_uuid'], ['users.uuid'], name='reviews_author_uuid_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_uuid'], ['products.uuid'], name='reviews_product_uuid_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('product_uuid', 'author_uuid', name='product_author_unique')
    )
    op.create_table('reviews_images',
    sa.Column('uuid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('review_uuid', sa.Uuid(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['review_uuid'], ['reviews.uuid'], name='reviews_images_review_uuid_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews_images')
    op.drop_table('reviews')
    # ### end Alembic commands ###
