"""user and cart models created

Revision ID: 70da7ea89888
Revises: 
Create Date: 2024-09-05 12:41:17.776870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70da7ea89888'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carts',
    sa.Column('uuid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('users',
    sa.Column('uuid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('cart_uuid', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('customer', 'support', 'warehouse_worker', 'courier', 'manager', name='userrole'), server_default=sa.text("'customer'"), nullable=False),
    sa.ForeignKeyConstraint(['cart_uuid'], ['carts.uuid'], name='users_cart_uuid_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('carts')
    # ### end Alembic commands ###
