"""product model created

Revision ID: 8821c7164fb0
Revises: b3c81848d309
Create Date: 2024-09-06 17:17:47.067217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8821c7164fb0'
down_revision: Union[str, None] = 'b3c81848d309'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_types',
    sa.Column('uuid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('parent_uuid', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['parent_uuid'], ['product_types.uuid'], name='product_type_product_type_uuid_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('products',
    sa.Column('uuid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('price_positive', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.String(length=5000), nullable=False),
    sa.Column('characteristics', sa.JSON(), nullable=True),
    sa.Column('discount', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('type_uuid', sa.Uuid(), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.ForeignKeyConstraint(['type_uuid'], ['product_types.uuid'], name='products_product_types_uuid_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('product_cart',
    sa.Column('product_uuid', sa.Uuid(), nullable=False),
    sa.Column('cart_uuid', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cart_uuid'], ['carts.uuid'], name='product_cart_cart_product_uuid_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_uuid'], ['products.uuid'], name='product_cart_product_uuid_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_uuid', 'cart_uuid')
    )
    op.create_table('user_favorite_products',
    sa.Column('user_uuid', sa.Uuid(), nullable=False),
    sa.Column('product_uuid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['product_uuid'], ['products.uuid'], name='user_favorite_products_product_uuid_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], name='user_favorite_products_user_uuid_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_uuid', 'product_uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_favorite_products')
    op.drop_table('product_cart')
    op.drop_table('products')
    op.drop_table('product_types')
    # ### end Alembic commands ###
